name: Frontend CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run lint
        run: |
          cd starter/frontend
          npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd starter/frontend
          npm ci

      - name: Run tests
        run: |
          cd starter/frontend
          npm run test

  build_and_push_ecr:
      name: Build and Push Frontend to ECR
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build Docker image for frontend
          env:
            REACT_APP_MOVIE_API_URL: "http://localhost:5000"
          run: |
            # Build the frontend Docker image
            docker build --file starter/frontend/Dockerfile --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL -t mp-frontend:latest starter/frontend

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR
          uses: aws-actions/amazon-ecr-login@v1

        - name: Verify Docker images
          run: docker images

        - name: Tag and push Docker image to ECR
          env:
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
          run: |
            docker tag mp-frontend:latest $ECR_REPOSITORY/frontend:latest
            docker push $ECR_REPOSITORY/frontend:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [push_to_ecr]
    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name cluster --region $AWS_REGION

      - name: Set image tag
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=$ECR_REPOSITORY/frontend:latest

      - name: Deploy to Kubernetes
        run: |
          cd starter/frontend/k8s
          kustomize build | kubectl apply -f -